# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171005_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
